permalink: pretty
markdown: kramdown

title: Two Factor Auth List
author: Josh Davis
description:
    List of sites with Two Factor Auth support which includes SMS, email,
    phone calls, hardware, and software.
url: https://dumbpasswordrules.com
repo: https://github.com/duffn/dumb-password-rules
img: img/logo.png
sass:
    style: compressed

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - vendor
    - websites_schema.yml
