permalink: pretty
markdown: kramdown

title: Dumb Password Rules
description: List of websites with dumb and smart password rules
#url: https://dumbpasswordrules.com
baseurl: /dumb-password-rules
repo: https://github.com/duffn/dumb-password-rules
img: img/logo.png
sass:
    style: compressed

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - vendor
    - websites_schema.yml
